// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvASB1V8yft0vtweo3e9c9TywX-IwDjXM',
    appId: '1:5308504649:web:cd5f845c4b5c1871e17d98',
    messagingSenderId: '5308504649',
    projectId: 'knowledgevault-a5cae',
    authDomain: 'knowledgevault-a5cae.firebaseapp.com',
    databaseURL: 'https://knowledgevault-a5cae-default-rtdb.firebaseio.com',
    storageBucket: 'knowledgevault-a5cae.appspot.com',
    measurementId: 'G-DKZL08PGTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChN65RdE21hqJG-K1ocDmQQ8LRaWn5Xgs',
    appId: '1:5308504649:android:3a7f6be46644e6bae17d98',
    messagingSenderId: '5308504649',
    projectId: 'knowledgevault-a5cae',
    databaseURL: 'https://knowledgevault-a5cae-default-rtdb.firebaseio.com',
    storageBucket: 'knowledgevault-a5cae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVz6r05siDeQhXzqP7TYpCcPbemz3OYm4',
    appId: '1:5308504649:ios:86632b92db054330e17d98',
    messagingSenderId: '5308504649',
    projectId: 'knowledgevault-a5cae',
    databaseURL: 'https://knowledgevault-a5cae-default-rtdb.firebaseio.com',
    storageBucket: 'knowledgevault-a5cae.appspot.com',
    iosClientId:
        '5308504649-djni8knqepquoauhcklmbrc3k2h276un.apps.googleusercontent.com',
    iosBundleId: 'com.example.knowledgevault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVz6r05siDeQhXzqP7TYpCcPbemz3OYm4',
    appId: '1:5308504649:ios:0029198169dee869e17d98',
    messagingSenderId: '5308504649',
    projectId: 'knowledgevault-a5cae',
    databaseURL: 'https://knowledgevault-a5cae-default-rtdb.firebaseio.com',
    storageBucket: 'knowledgevault-a5cae.appspot.com',
    iosClientId:
        '5308504649-la0tjq3ph8i528m8t7rti7ffspci9lhi.apps.googleusercontent.com',
    iosBundleId: 'com.example.knowledgevault.RunnerTests',
  );
}
